### ISSUE TITLE
Work in raspberry pi4? 

### ISSUE THREAD

**Issue by rdaguerre** [colin-nolan/docker-shinobi#1]
I try use and not work for me? Anyone try?
Thanks

**Comment by kiddyfurby** [comment]
Yes it does work very well.  What problem are you facing?

**Comment by colin-nolan** [comment]
I have been using this setup on an RPi4 too. It's not apparent what the issue was (if any) so I'll close this issue now. Feel free to re-open/open a specific issue if one occurs.
